name: CI
run-name: Build
on: [push]

jobs:
  gradle:
    runs-on: windows-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle wrapper
        env:
          CI: true
        id: gradle
        run: .\gradlew build
      - name: Upload common build
        uses: actions/upload-artifact@v3
        with:
          name: common
          path: build/libs/
      - name: Upload fabric build
        uses: actions/upload-artifact@v3
        with:
          name: fabric
          path: fabric/build/libs/
      - name: Upload forge build
        uses: actions/upload-artifact@v3
        with:
          name: forge
          path: forge/build/libs/